#!/bin/bash
declare -A matrix
num_columns=4
num_rows=9

for ((i=1;i<=num_columns;i++)) do
    for ((j=1;j<=num_rows;j++)) do
        matrix[$i,$j]=$RANDOM
    done
done

f1="%$((${#num_columns}+1))s"
f2=" %9s"

printf "$f1" ''
for ((i=1;i<=num_columns;i++)) do
    printf "$f2" $i
done
echo

for ((j=1;j<=num_rows;j++)) do
    printf "$f1" $j
    for ((i=1;i<=num_columns;i++)) do
        printf "$f2" ${matrix[$i,$j]}
    done
    echo
done
