#!/bin/bash

declare -A matrix
num_columns=1
num_rows=0

function visualizar() {
    f1="%$((${#num_columns}+1))s"
    f2=" %9s"

    printf "$f1" ''
    for ((i=0;i<=num_columns;i++)) do
        printf "$f2" $i
    done
    echo

    for ((j=0;j<num_rows;j++)) do
        printf "$f1" $(($j+1))
        for ((i=0;i<=num_columns;i++)) do
            printf "$f2" ${matrix[$i,$j]}
        done
        echo
    done
}

function cargar(){
    for palabra in `cat $1`
    do  
        if [ $num_rows -eq 0 ]
        then
            matrix[0,$num_rows]=$palabra
            matrix[1,$num_rows]=0
            let num_rows=$num_rows+1
        else   
            pos=`buscar $palabra`
           
            if [ $pos -eq -1 ]
            then  
                matrix[0,$num_rows]=$palabra
                matrix[1,$num_rows]=0
                let num_rows=$num_rows+1
            else
                matrix[1,$pos]=$((${matrix[1,$pos]}+1))
            fi
        fi
    done
}

function buscar(){
    local encontrado=-1
    local i=0
    
    while [[ $encontrado -eq -1 && $i -le $num_rows ]]
    do
        if [[ ${matrix[0,$i]} == $1 ]]
        then
            encontrado=$i
        fi
        let i=$i+1
    done
    echo $encontrado
}

cargar "texto"
visualizar
